### ISSUE TITLE
Not works with mod outside default of the game...

### ISSUE THREAD

**Issue by FirenzeIT** [GMNGjoy/FS22_SpawnPalletsStacked#2]
Hello, this mod it's very useful and realistic, but not works with other mod outside of the default game (example productions/serres of Rvamp, or Greenhouses With Pallets and others productions/factories, only on default's mod) :-( It's possible to fix them for all general?? Or it's impossible?? at least for the modhub's greenhouses and factories, it would be the top

**Comment by GMNGjoy** [comment]
Thank you for your report / question!

The overall intention of the _Spawn Pallets Stacked_ mod is specifically to work with any building or mod that has pallet spawn locations, and with any kind/size of pallet. From all of my testing, I have not found any single mod on Modhub (or otherwise) that this mod does not work for, within the guidelines of the mod.

I'm curious about your report - as the statement is made in a very generalized way stating that the _Spawn Pallets Stacked_ mod does _not_ work for a large series of mods/types of mods - but as I just spoke about, it's _designed_ to do just that. Have you tried using the mod and are experiencing issues? If you have any specific mods that you have found that the spawning does _not_ work with, please let me know and I'll look into it!

The screenshots here and on ModHub show primarily (but not only) base game buildings, due to the audience of the release - since it's not possible without editing/creating copies of base game productions to get those productions with stacked pallets - thereby showing that it works as intended. This is one of the major selling points of the mod itself.

The few cases where the _Spawn Pallets Stacked_ mod will "prevent failure" and not stack pallets or not double-up are as follows:

- Won't double up a single row if there is not enough space in the spawn location to do so. This is easily overcome by adding a custom configuration for the building in question to force different positioning or spacing of the double-up row. Examples of how to do that are found on the [README.md](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked) file, specifically about changing the `doubleUpShift` setting.

- Won't stack higher than `2m` tall by default (which is a configurable setting), so if the pallets that are spawning are greater than `1m` tall, then it won't stack a second level since it can't within the `2m` limit. This setting is also overridable by either a single-building configuration or a global setting. Again, see the [README.md](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked) for more information on setting the `spawnHeight`.

- Sometimes the stacking logic will fail to properly stack pallets when a production has multiple-sized pallets; in those cases, if the pallets fall over, you can use the configuration file to prevent stacking. See the [README.md](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked) for more information on the `shouldStack` setting.

- If the mod/building already has stacked pallets, then _Spawn Pallets Stacked_ mod will skip trying to stack for that mod/building. This is the case for many of the Dragons' Den and / or Production Revamp productions, but not all. This mod will check each spawn point (regardless of who wrote it) and decide whether to stack or not.

- If the mod/building has defined pallets incorrectly (where the XML thinks the pallet is much smaller or bigger than the model of said pallet), it may hit any of the previous limits above - there is nothing that I can do from my side to fix this issue, it's up to the original mod/building to setup their custom pallets properly.

**Comment by FirenzeIT** [comment]
Hello, i tried all way for doing something works with other mods, but i break the mod and i redownloaded... I add below 3 screenshots from 3 different greenhouses, which i write not works (1 works because it's a default base game greenhouse)..

![Empty_Pallets_Prod_Revamp_Ed](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked/assets/113168067/65890733-74c1-41a2-814a-2362bc4c6c41)
![Greenhouse_default_base_game](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked/assets/113168067/a5fbd740-2912-4426-bfc7-3a98b26b7524)
![Greenhouses_with_Pallets](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked/assets/113168067/da0e7da0-5f32-4392-90fa-c5bd8276886d)

**Comment by GMNGjoy** [comment]
Thank you for those screenshots!

What would greatly help is if you could possibly share the name of those two greenhouse  mods and / or the ModHub link where you got them from... The screenshots appear to be in another language other than english, and it's hard to tell from the screenshots which mod those greenhouses are from. 

As far as the mod working or not - if you look at the screenshots where the pallets are not spawning properly,  you can tell that with the revamp one that the mod is attempting to do it’s job (the line of pallets is moved slightly to try to get two rows in, for the `doubleUp` feature) but i suspect it was unable to fit a second row so the safety checks caused the spawing to exit without adding the stacking layers. that’s expected for most greenhouses as they have a very shallow spawn area. I suspect you'd have a line in your log where that failure is caught and reported. (if you add a configuration of `<debugFull>true</debugFull>` in the `settings` section it will give you a higher level of debug output)

In the code for the mod, there's a section that attempts to never "double up" for any item of `type="greeenhouse"` - in this case, suspect that the mods that you're demoing are not listed as a "greenhouse" somehow, and the logic is falling over. This is not something that I expected, but is something I can look into making an update to properly accommodate.

```
		-- don't doubleUp greenhouses
		if tostring(productionItem.typeName) == "greenhouse" then
			adjustment.shouldDoubleUp = false
		end
```

But, you can _easily_ add a quick configuration line to your `SpawnPalletsStacked.xml` file in your `modSettings` folder right now that would look something like the following, which should fix the problem by setting the `shouldDoubleUp`  feature to `false`

```
        <adjustment
            filename="FS22_YourGreenHouseModName/largeGreenhouse.xml"
            shouldDoubleUp="false" 
        />
```

If you send me the name / url of the mods in question, I'll be happy to test and give you a working `adjustment` to get you on your way!

**Comment by FirenzeIT** [comment]
Hi, i just tried modify that but i broken mod and need to redownloaded, however i add a screenshots below with there link site each... (both not stacked, but with default base greenhouse, it's stacked without any problems)...

**_Greenhouses with Pallets:_**
![1248130_20240314013734_1](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked/assets/113168067/085d67ab-56de-4726-9696-9f71dafd84fc)
https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=238185&title=fs2022

**_ProductionRevamp Productions (greenhouses it's included):_**
![1248130_20240314013421_1](https://github.com/GMNGjoy/FS22_SpawnPalletsStacked/assets/113168067/82685a72-fdf7-47c4-b46f-5360c85681db)
https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=243667&title=fs2022


**_Also with this others greenhouse:_**

https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=250574&title=fs2022

https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=252317&title=fs2022

**Comment by GMNGjoy** [comment]
The above greenhouses linked all have products that *can* be spawned that will prevent stacking. This is not an issue, and the mod is working as expected.
